GET http://localhost:3000

### test
GET http://localhost:3000/auth/asd

### 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "userName":"abhi53",
    "email":"abhi531@gmail.com",
    "password":"Create53pass",
    "role":"admin"  
}

### 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"abhi531@gmail.com",
    "password":"Create53pass"
}

### 
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjY1YjBlZTEzZWFkMDdhYjY5ZDIzZTE1IiwiaWF0IjoxNzE3MzIxNzUwLCJleHAiOjE3MTczMjUzNTB9.J7ngncu2oBNEeY4Kg6k72-guUIZy8l1qfzhoPs3MHPM"
}

###
POST http://localhost:3000/auth/validateToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjY1YjBlZTEzZWFkMDdhYjY5ZDIzZTE1IiwiaWF0IjoxNzE3MzIxNzUwLCJleHAiOjE3MTczMjUzNTB9.J7ngncu2oBNEeY4Kg6k72-guUIZy8l1qfzhoPs3MHPM