GET http://localhost:3000

### test
GET http://localhost:3000/auth/asd

### 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "userName":"abhi53",
    "email":"kari5443@gmail.com",
    "password":"Create53pass",
    "role":"admin"  
}

### 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"abhi531@gmail.com",
    "password":"Create53pass"
}

### 
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjY1YjBlZTEzZWFkMDdhYjY5ZDIzZTE1IiwiaWF0IjoxNzIzNDA2MzQyLCJleHAiOjE3MjM0MDk5NDJ9.4fwuEhx2m2QCj-35-c3pExJjYDTP6bIC1MDFwl3UFP4"
}

###
POST http://localhost:3000/auth/validateToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjY1YjBlZTEzZWFkMDdhYjY5ZDIzZTE1IiwiaWF0IjoxNzIzNDA3NDEyLCJleHAiOjE3MjM0MTEwMTJ9.45kUUVoB0QHsGXedaXQOWildGSrazpuztN1C2GPYutY