GET http://localhost:3000

### test
GET http://localhost:3000/auth/asd

### 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "userName":"abhi53",
    "email":"kari53@gmail.com",
    "password":"Create53pass",
    "role":"admin"  
}

### 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"abhi531@gmail.com",
    "password":"Create53pass"
}

### 
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjY1ZWI3NmYzYzM1NWIzYjg2NDA5Zjg3IiwiaWF0IjoxNzE3NDgzMzc1LCJleHAiOjE3MTc0ODY5NzV9.xDrBzeMm4b0BKC7_M_VEOeLXi9tbC1AHEB-kWwxDyzE"
}

###
POST http://localhost:3000/auth/validateToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjY1ZWI3NmYzYzM1NWIzYjg2NDA5Zjg3IiwiaWF0IjoxNzE3NDgzMzc1LCJleHAiOjE3MTc0ODY5NzV9.xDrBzeMm4b0BKC7_M_VEOeLXi9tbC1AHEB-kWwxDyzE